//loaders
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';

// login
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';